config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'users#index'
  end


  namespace :api do
    namespace :v1 do
      resources :projects
    end
  end 
  resources :technologies
  resources :projects 
  resources :project_technologies
  # Defines the root path route ("/")

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
      return unless user.present?
      can :read, :all
      return unless user.admin?
      can :manage, :all
    
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    
    has_many :project_technologies, dependent: :destroy
    has_many :technologies, through: :project_technologies
    has_many_attached :images
    validates :name, presence: true
    validates :name, uniqueness: true

    def photos
        images.map{|p| Rails.application.routes.url_helpers.rails_blob_url(p) }
    end
end

app/models/project_technology.rb
class ProjectTechnology < ApplicationRecord
    
    belongs_to :project
    belongs_to :technology
end

app/models/technology.rb
class Technology < ApplicationRecord
      
    
    has_many :project_technologies, dependent: :destroy
    has_many :projects, through: :project_technologies
    
        validates :name, presence: true
        validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_one_attached :image

        has_many :projects, dependent: :destroy
        has_many :project_technologies, through: :projects
        has_many :technologies, through: :project_technologies

        def admin?
          self.role == "admin"
        end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController
    def index
        @projects = Project.all
        render json: ProjectSerializer.new(@projects).serializable_hash
    end


    def show 
        @project = Project.find(params[:id])
        render json: ProjectSerializer.new(@project).serializable_hash[:data][:attributes]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_get
    def set_get
        @user=current_user
    end

    protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update) do |u|
            u.permit(:name,:image, :email, :password, :current_password)
          end
    end


end

app/controllers/project_technologies_controller.rb
class ProjectTechnologiesController < ApplicationController
    before_action :authenticate_user!
def destroy
    @project_technology = ProjectTechnology.find_by(project_id: params[:id])
    return if current_user.role=="user"
    if @project_technology.destroy
        redirect_to @project
    end
end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user! 
    def index
        @projects = Project.all
    end


    def new
        @project = Project.new
    end

    def show 
        @project = Project.find(params[:id])
    end

    def create
        @project = Project.new(project_params)
        return if current_user.role=="user"
        if @project.save
            redirect_to @project
        else
            render :new, status: :unprocessable_entity
          end
    end
 
    def destroy
        @project = Project.find(params[:id])
        return if current_user.role=="user"
        if @project.destroy
            redirect_to projects_path   
        end
    end
    
    def edit
        @project =Project.find(params[:id])
      end

     def update
        @project = Project.find(params[:id])
        return if current_user.role=="user"
        if @project.update(project_params)
            redirect_to @project
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def project_params
        params.require(:project).permit(:name,:place,:title,:description,:livesource,:sourcecode,:thumb,images: [], technology_ids: [])
    end

end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :authenticate_user!

    def index
        @tech = Technology.all
      end
    
      def new
        @tech = Technology.new
      end
    
      def create
        @tech = Technology.new(tech_params)
         return if current_user.role=="user"
        if @tech.save
          redirect_to @tech
        else
          render :new, status: :unprocessable_entity
        end
      end

      def destroy
        @tech = Technology.find(params[:id])
        return if current_user.role=="user"
      if @tech.destroy
        redirect_to technologies_path
      end
    end
    
      private
        def tech_params
          params.require(:technology).permit(:name)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def index
        @user = current_user
    end
    
    # GET /users/1
    # GET /users/1.json
end

app/helpers/api/v1/projects_helper.rb
module Api::V1::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/project_technologies_helper.rb
module ProjectTechnologiesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_mobile.html.erb
<div class="topnav">
<% if user_signed_in? %>
  <a href="#home" class="active">Admin Panel</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
  <i class="fa fa-bars"></i>
</a>
<nav id="myLinks" class="links">
 <h4><%=@user.name%><h4>
     <ul>  
    <% if @user.image.attached? %>
        <image src="<%=url_for(@user.image)%>" alt="logo" width="100" height="100">
     <%end%>
         <li><%= link_to "Projects", projects_path, class: ["", ("active" if request.path == projects_path )]%></li>
         <li><%= link_to "Add New Project", new_project_path ,class: ["", ("active" if request.path == new_project_path)]%></li>
         <li><%= link_to "Add New Technology", new_technology_path ,class: ["", ("active" if request.path == new_technology_path )]%></li>
         <li><%=link_to "Profile" ,edit_user_registration_path,class: ["", ("active" if request.path == edit_user_registration_path )]%> </li>
         <% if user_signed_in? %>
         <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, :class=>"login-s" %>
         <%end%>
     </ul>
     <div class="message"> 
     <% if @user.role=="user"%>
     <h4>As a Guest you can only view. No edits and creates. Thanks for understanding</h4>
     <%end%>
     </div>
 </nav>
 <%end%>
</div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioAdmin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/mobile" %>
    <div class="main">
       <%if user_signed_in?%>
     <div class="side-nav">
       <%=render "devise/shared/nav"%>
     </div>
    
    <script>
    
function myFunction() {
  var x = document.getElementById("myLinks");
  if (x.style.display === "block") {
    x.style.display = "none";
  } else {
    x.style.display = "block";
  }
}
</script>

<%end%>
 <div class="content">
    <%= yield %>
  </div>
  </div>
  </body>

</html>

app/views/projects/edit.html.erb
<div class="new-cont">
<h1>Edit</h1>

<%= form_with model: @project do |form| %>
  <div class="a">
    <%= form.label :name ,:class=>"label" %><br>
    <%= form.text_field :name,:class=>"area" %>
  </div>
  <div class="a">
  <%= form.label :place, :class=>"label" %><br>
  <%= form.text_field :place,:class=>"area" %>
</div>
<div class="a">
<%= form.label :title, :class=>"label" %><br>
<%= form.text_field :title,:class=>"area" %>
</div>
<div class="a">
<%= form.label :description ,:class=>"label " %><br>
<%= form.text_area :description,:class=>"area desc" %>
</div>
<div class="a">
<%= form.label :livesource ,:class=>"label"%><br>
<%= form.text_field :livesource,:class=>"area" %>
</div>
<div class="a">
<%= form.label :sourcecode,:class=>"label"%><br>
<%= form.text_field :sourcecode,:class=>"area" %>
</div>
<div class="a">
<%=form.label "Profile image" ,:class=>"label m2"%>
<div class="img-upload  p3"><%=form.file_field :images , multiple: true,:class=>""%></div>
</div>
<div class="tech-a" >
<div class="label m2"><%=form.label "Add Technologies" ,:class=>"" %></div>
<div class="tech-list">
 <%= form.collection_check_boxes:technology_ids, Technology.all, :id, :name,{mutliple: true} ,:class=>"" do |b|%>
  <%=b.label(class: ""){b.check_box + b.text}%>
 
<%end%>
</div>
</div>

  <div class="a">
    <%= form.submit :class=>"submit"%>
  </div>
  
<% end %>
</div>

app/views/projects/index.html.erb
<button class="api"><%=link_to "View JSON","api/v1/projects" %></button>
<div class="project-card-cont">
<% @projects.each do |project|%>
    <div class="project-link">
      <%=link_to project_path(project) do %>
       
        <h2><%=project.name[0..20]%></h2>
        <%end%>
        <%=link_to edit_project_path(project) do %>
        <div class="span">Edit</div>
        <%end%>
     </div>
<%end%>
</div>

app/views/projects/new.html.erb
<div class="new-cont">
<h1>New Project</h1>

<%= form_with model: @project do |form| %>
  <div class="a">
    <%= form.label :name ,:class=>"label" %><br>
    <%= form.text_field :name,:class=>"area" %>
  </div>
  <div class="a">
  <%= form.label :place, :class=>"label" %><br>
  <%= form.text_field :place,:class=>"area" %>
</div>
<div class="a">
<%= form.label :title, :class=>"label" %><br>
<%= form.text_field :title,:class=>"area" %>
</div>
<div class="a">
<%= form.label :description ,:class=>"label " %><br>
<%= form.text_area :description,:class=>"area desc" %>
</div>
<div class="a">
<%= form.label :livesource ,:class=>"label"%><br>
<%= form.text_field :livesource,:class=>"area" %>
</div>
<div class="a">
<%= form.label :sourcecode,:class=>"label"%><br>
<%= form.text_field :sourcecode,:class=>"area" %>
</div>
<div class="a">
<%=form.label "Profile image" ,:class=>"label m2"%>
<div class="img-upload  p3"><%=form.file_field :images , multiple: true,:class=>""%></div>
</div>
<div class="tech-a" >
<div class="label m2"><%=form.label "Add Technologies" ,:class=>"" %></div>
<div class="tech-list">
 <%= form.collection_check_boxes:technology_ids, Technology.all, :id, :name,{mutliple: true} ,:class=>"" do |b|%>
  <%=b.label(class: ""){b.check_box + b.text}%>
 
<%end%>
</div>
</div>

  <div class="a">
    <%= form.submit :class=>"submit"%>
  </div>
  
<% end %>
</div>

app/views/projects/show.html.erb
<button class="api"><%=link_to "View JSON",api_v1_project_path(@project) %></button>
<div class="project-show-cont">
  <div class="info-cont">
     <h1><%=@project.name%></h1>
     <h2><%=@project.title%></h2>
     <p> <%=@project.description%></p>
     <p><%=@project.place%></p>
  </div>
  <div class="links-cont">
    <div><%=link_to "Live Source" , @project.livesource , target: '_blank'%></div>
    <div><%=link_to "Source Code" , @project.sourcecode , target: '_blank'%></div>
    <div><%= button_to  "Delete Project ", project_path(@project), method: :delete %></div>
    <div><%= link_to "Edit Project", edit_project_path(@project) %></div>
  </div>
  <div class='img-cont'>
    <% if @project.images.attached? %>
    <% @project.images.each do |image| %>
        <image src="<%=url_for(image)%>" alt="logo"  class="images">
       <%end%>
     <%end%>
    </div>
    <div class='project-tech-cont'>
    <h3>Technologies</h3>
    <div class='tech-cont'>  
       <%@project.technologies.each do |technology|%>
        <div class="tech">    
              <div><%=technology.name%></div> 
              <div class="btn"><%=button_to "X",project_technology_path(@project.id), method: :delete%></div>
        </div>
        <%end%>
        </div>
    </div>
</div>

app/views/technologies/new.html.erb
<div class= "add-tech">
<h1>New Technology</h1>

<%= form_with model: @tech do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, :class=>"field"%>
  </div>
  <% @tech.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
  <div>
    <%= form.submit :class=>"tech-submit" %>

    

  </div>
<% end %>
</div>